graph TD
    F1["fib(4)"] --"4-1"--> F2["fib(3)"]
    F1 --"4-2"--> F3["fib(2)"]
    F3 --"2-1"--> F4["fib(1)"]
    F3 --"2-2"--> F5["fib(0)"]
    F2 --"3-1"--> F6["fib(2)"]
    F2 --"3-2"--> F7["fib(1)"]
    F6 --"2-1"--> F8["fib(1)"]
    F6 --"2-2"--> F9["fib(0)"]
    F4 -- "1" --> F10["1"]
    F7 -- "1" --> F11["1"]
    F8 -- "1" --> F12["1"]
    F10 -- " sum " --> F13["sum = 3"]
    F11 -- " sum " --> F13
    F12 -- " sum " --> F13